In [2]:
import numpy as np

def cross_product(a,b):
    return np.array([a[1]*b[2]-a[2]*b[1],
                     a[2]*b[0]-a[0]*b[2],
                     a[0]*b[1]-a[1]*b[0]])

vec1 = np.array([1,-7,1])
vec2 = np.array([5,2,4])

print(np.cross(vec1,vec2))
print(cross_product(vec1,vec2))

[-30   1  37]
[-30   1  37]


In [3]:
vec1 = np.array([[6,5,4,3],
                 [7,8,9,10]])


print(vec1.T)

[[ 6  7]
 [ 5  8]
 [ 4  9]
 [ 3 10]]


In [8]:
a = np.array([[2,1,3],
              [1,0,2],
              [4,1,8]])


print(np.linalg.det(a))

-1.0


In [11]:
nega = np.linalg.inv(a)
nega

array([[ 2.,  5., -2.],
       [ 0., -4.,  1.],
       [-1., -2.,  1.]])

In [10]:
a@nega

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
a = np.array([[1,2],
              [2,-1]])
b = np.array([1,7])

np.linalg.inv(a)@b

array([ 3., -1.])

In [18]:
mat1 = np.array([[1,-2,-1],
                 [2,-1,0],
                 [0,1,1]])
np.linalg.det(mat1)

np.float64(1.0)