In [3]:
import torch
from torch import nn
import torch.nn.functional as F

import matplotlib.pyplot as plt


In [4]:
torch.cuda.is_available()

False

In [5]:
import os
os.cpu_count()

10

In [1]:
import numpy as np

A = np.array([
    [-1,  0, -1, -1,  0, -1,  0],
    [ 0,  1, -2, -1,  1, -1,  1],
    [-2,  1,  0, -1,  0,  0,  0],
    [ 0,  1,  1,  1,  0,  1,  0],
    [-1, -2,  1,  0, -2,  0, -1],
    [ 4, -1,  1,  2,  1,  1,  0],
    [ 0,  2,  2,  1,  1,  2,  0]
])

B = np.array([0,1,1,1,-2,-1,2])
C = A @ B

A @ C

array([ 0,  0, -1,  0,  0,  1, -1])

In [2]:
P_inverse = np.array([[2,-5,-28,6,-6,-1,1],
          [-1,2,1,-2,0,-1,2],
          [0,-1,-15,1,-5,-1,2],
          [0,-2,-8,2,-3,0,0],
          [0,4,14,-4,11,1,-3],
          [0,-5,-11/2,5,-21/6,3/2,-5/2],
          [0,3/2,9/4,-3/2,5/4,-1/4,3/4]])

P = np.array([[0,0,-1,0,-0.5,-0.5,-1],
              [1,1,-1,0,0.5,-0.5,-1],
              [0,1,0,-1,0,0.5,-1],
              [0,1,2,0,1,1.5,1],
              [0,-2,1,0,0,-.5,1],
              [0,-1,-1,1,0,-.5,1],
              [0,2,1,-1,0,2,0]])

P_inverse_true = np.linalg.inv(P)

In [3]:
P_inverse_true @ A @ P

array([[ 4.44089210e-16, -1.11022302e-16, -1.11022302e-16,
         0.00000000e+00,  1.11022302e-16, -2.22044605e-16,
         0.00000000e+00],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -2.22044605e-16, -4.16333634e-16,  0.00000000e+00,
        -1.66533454e-16],
       [-5.55111512e-17,  1.00000000e+00, -3.55271368e-16,
         1.33226763e-16, -4.44089210e-16, -4.88498131e-16,
         0.00000000e+00],
       [ 2.44249065e-16,  2.22044605e-16,  1.00000000e+00,
         5.55111512e-17,  2.49800181e-16, -1.11022302e-16,
         0.00000000e+00],
       [ 0.00000000e+00,  1.85037171e-16, -1.85037171e-16,
         1.85037171e-16,  3.33066907e-16,  2.40548322e-16,
         1.11022302e-16],
       [ 0.00000000e+00,  4.44089210e-16, -2.22044605e-16,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        -2.22044605e-16],
       [ 0.00000000e+00,  2.22044605e-16,  1.11022302e-15,
        -2.22044605e-16,  4.44089210e-16,  1.00000000e+00,
         8.8817842

In [6]:
result = P @ A @ P_inverse_true

[[0 if i < 0.0001 else 1 if i < 1.00003 and i > 0.9999 else i for i in row] for row in result]
# [[i for i in row] for row in result]
answer = [[i for i in row] for row in result]

np.set_printoptions(suppress=True, precision=10) # Suppress and set precision
print(answer)

[[np.float64(-7.250000000000001), np.float64(0.5), np.float64(1.2499999999999996), np.float64(-4.375000000000001), np.float64(-0.7500000000000002), np.float64(0.12500000000000003), np.float64(-0.12499999999999993)], [np.float64(-17.250000000000004), np.float64(-1.5), np.float64(4.25), np.float64(-9.375000000000002), np.float64(-3.7500000000000004), np.float64(-0.875), np.float64(-2.125)], [np.float64(-10.000000000000002), np.float64(2.0), np.float64(4.0), np.float64(-5.5), np.float64(0.4999999999999991), np.float64(2.0), np.float64(6.938893903907228e-16)], [np.float64(7.500000000000002), np.float64(1.0), np.float64(-0.5), np.float64(4.750000000000001), np.float64(2.0000000000000004), np.float64(1.25), np.float64(0.7500000000000001)], [np.float64(10.500000000000004), np.float64(-4.0), np.float64(-2.5), np.float64(5.75), np.float64(-0.9999999999999989), np.float64(-2.75), np.float64(-1.2500000000000004)], [np.float64(16.000000000000004), np.float64(0.0), np.float64(-6.0), np.float64(7.50

In [8]:
[[0 if i < 0.0001 else 1 if i < 1.00003 and i > 0.9999 else i for i in row] for row in result]
[[int(i) for i in row] for row in result]

[[-7, 0, 1, -4, 0, 0, 0],
 [-17, -1, 4, -9, -3, 0, -2],
 [-10, 2, 4, -5, 0, 2, 0],
 [7, 1, 0, 4, 2, 1, 0],
 [10, -4, -2, 5, 0, -2, -1],
 [16, 0, -6, 7, 2, -1, 1],
 [-1, 6, 2, 0, 3, 5, 2]]

In [6]:
G = np.array([0,4,1,0,0,0,0])

A @ G

array([-1,  2,  4,  5, -7, -3, 10])

In [7]:
A @ np.array([0,0,-1,0,0,1,-1])

array([0, 0, 0, 0, 0, 0, 0])

In [8]:
A @ A

array([[-1, -1, -1, -1, -1, -1,  0],
       [-1, -1, -1, -1, -1, -1,  0],
       [ 2,  0, -1,  0,  1,  0,  1],
       [ 2,  2,  0,  1,  2,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  0],
       [-3, -1,  2,  0, -2,  0, -2],
       [ 3,  1,  0,  1,  2,  1,  1]])

In [13]:
A @ np.array([-1/2,1/2,0,1,0,0,0])

array([-0.5, -0.5,  0.5,  1.5, -0.5, -0.5,  2. ])

In [14]:
def recursion(n):
    print(n)
    recursion(n)

recursion(1)

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


RecursionError: maximum recursion depth exceeded

In [17]:
try:
    5/0
except ZeroDivisionError:
    print("Fefes")

Fefes


In [25]:
n = 1

try:
    result = 10 / n
except Exception as e:
    print("No no no")
else:
    print(result)
finally:
    print("hello")

10.0
hello


In [33]:
arr = [1,2,3,4,5,6, -3]
func = lambda x: x > 0

print(all(func(i) for i in arr))
any(func(i) for i in arr)

False


True

In [36]:
result = list(filter(func, arr))
for i in result:
    print(i)

1
2
3
4
5
6


In [38]:
tuple(range(1,11))

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [49]:
def decorator_func(function):
    def some_func(function):
        print(f"the name of the original function: {function.__name__}")
        return function()
    return some_func

@decorator_func
def display(n):
    print(f"n: {n}")

display("hello")

AttributeError: 'str' object has no attribute '__name__'

In [56]:
def decorator_func(function):
    def wrapper(*args, **kwargs):
        print(f"wrapper: {args} , {kwargs}")
        return function(args, kwargs)
    return wrapper


@decorator_func
def display2(name,age):
    print(f"original: {name} , {age}")


display2("hello", 124, privet=666)

wrapper: ('hello', 124) , {'privet': 666}
original: ('hello', 124) , {'privet': 666}


In [94]:
class some:
    @staticmethod
    def func(name):
        print(f"hello {name}")

    variable1 = "FUNC 2"
    @classmethod
    def func2(name):
        print(f"Hello from func2, name: {name.variable1}")

    def func3(name):
        print(f"func3, name: {name}")


In [95]:

some.func("nureke")

hello nureke


In [101]:
some.func2()

Hello from func2, name: FUNC 2


In [97]:
some.func3("hello")

func3, name: hello


In [98]:
var = some()

var.func("nureke")

hello nureke


In [102]:
var.func2()

Hello from func2, name: FUNC 2


In [103]:
var.func3("nureke")

TypeError: some.func3() takes 1 positional argument but 2 were given

In [115]:
def outer_function():
    def inner_function():
        print("inner function")
    return inner_function

main = outer_function()
main()

inner function


In [116]:
main()

inner function


In [155]:
def outer_function():
    count = 0
    def inner_function():
        nonlocal count
        count += 1
        print(f"count: {count}")
    return inner_function

main2 = outer_function()
main2


<function __main__.outer_function.<locals>.inner_function()>

In [194]:
main2()

count: 39


In [195]:
def multiplier(factor):
    def multiply(x):
        return x * factor
    return multiply

main3 = multiplier(4)
main3

<function __main__.multiplier.<locals>.multiply(x)>

In [196]:
main3(10)

40

In [198]:
main4 = multiplier(5)
main4(6)

30

In [204]:
from functools import reduce
list1 = [1,2,3,4,5,-1,-1]
g = lambda x,y: x * y
reduce(g,list1)

120